### ISSUE TITLE
Defense.py file not working

### ISSUE THREAD

**Issue by AdnanEshan** [git-disl/DataPoisoning_FL#8]
After running the command,it gives this error "Traceback (most recent call last):
  File "/content/DataPoisoning_FL/defense.py", line 69, in <module>
    model_files = sorted(os.listdir(MODELS_PATH))
FileNotFoundError: [Errno 2] No such file or directory: '/absolute/path/to/models/folder/1823_models'

**Comment by rajaabn** [comment]
I get the same error when running defense.py
File "/content/DataPoisoning_FL/defense.py", line 69, in
model_files = sorted(os.listdir(MODELS_PATH))
FileNotFoundError: [Errno 2] No such file or directory: '/absolute/path/to/models/folder/1823_models'
